Passing Arguments to the Executor
blocklessnetwork/b7s pull request #129
Opened 2024-01-09 20:45 UTC by dmikey

The old way had this being 

```json
{
    "parameters" : [{
        "name" : "foo",
        "value" : "bar"
    }]
}
```

We lost some context along the way, and this was a bug.

We should be getting.

```json
{
    "arguments" : [{
        "foo",
        "bar"
    }]
    "parameters" : [{
        "name" : "foo",
        "value" : "bar"
    }]
}
```

I need to double check the runtime if takes flags correctly.

2024-01-10 18:13 UTC, xmariachi approved these changes
LGTM

2024-01-10 18:14 UTC, xmariachi commented
> The old way had this being
> 
> ```json
> {
>     "parameters" : [{
>         "name" : "foo",
>         "value" : "bar"
>     }]
> }
> ```
> 
> We lost some context along the way, and this was a bug.
> 
> We should be getting.
> 
> ```json
> {
>     "arguments" : [{
>         "foo",
>         "bar"
>     }]
>     "parameters" : [{
>         "name" : "foo",
>         "value" : "bar"
>     }]
> }
> ```
> 
> I need to double check the runtime if takes flags correctly.

If the new way is to have 
config/env_vars, please let's also re-edit original comment :) Thanks!

2024-01-15 10:59 UTC, Maelkum requested changes
I'm not sure if I'm missing something, but this doesn't seem to bring any new functionality?

2024-01-15 10:59 UTC, Maelkum commented on executor/executor.go
> +	cfg.DriversRootPath = cfg.RuntimeDir + "/extensions"
`filepath.Join` will use the correct path separator for the OS:

```suggestion
	cfg.DriversRootPath = filepath.Join(cfg.RuntimeDir, "extensions")
```

2024-01-15 10:59 UTC, Maelkum commented on executor/command.go
> +			args = append(args, param.Name + "=" + param.Value)
What's the difference between arguments and parameters? I don't think this brings anything compared to the previous version, functionality-wise. Speaking from the POV of just _I am executing a binary and giving it some arguments_.

The same thing can be done with the previous version by using:

```json
{
	"parameters": [
		{ "value": "key1=val1" },
		{ "value": "key2=val2" 	}
	]
}
```

I don't think executables typically use `key=val` syntax for CLI flags (with no dashes or anything). Not enough that we have such first-class support for that syntax.

Plus, with the previous version we can support all variants:

a) key-value pairs
```go
	 []execute.Parameter{
		{Value: "key1=val1"},
		{Value: "key2=val2"},
		{Value: "key3=val3"},
	}
```

b) Typical UNIX flags:

```go
	 []execute.Parameter{
		{Value: "--file"},
		{Value: "/tmp/whatever.txt"},
		{Value: "--size"},
		{Value: "64MB"},
	}
```

c) Windows whatevers:

```go
	[]execute.Parameter{
		{Value: "dir"},
		{Value: "/s"},
		{Value: "/q"},
	}
```

If anything, we can just remove `Parameters` completely and just use a string array.

2024-01-23 03:04 UTC, closed without merging