Worker executor response signature support
blocklessnetwork/b7s pull request #154
Opened 2024-06-15 02:02 UTC by zees-dev

# Context

This PR adds support for b7s workers to optionally support signing responses (using any arbitrarily provided signature scheme/function as an executor option)

- This is specifically useful when using b7s node as a lib, where you'd want the worker to sign responses with custom provided signature scheme/algorithm (such as in the case of using b7s as AVS)
- With this change, the head node would return aggregated worker responses, in addition to their respective signatures (assuming the workers opted into signing with some desired scheme)

2024-06-20 16:03 UTC, dmikey commented
Overall I like this. I think it works well with having a signer configurable to a node. I think we will need to shift this into support multiple signing options, but at face value I see now problem with this approach.

2024-06-20 16:03 UTC, dmikey approved these changes

2024-06-23 04:00 UTC, zees-dev commented
@dmikey Additionally added support for providing metadata from workers.
With the metadata injection support; one can say we do not need to add the optional signature override - since that can be part of the metadata response.
^ Hence, do let me know if I should remove the option to override the signature.

2024-06-24 14:25 UTC, Maelkum requested changes
Code-wise I think this is great! However I feel this is a little confused when it comes to some concepts, would love to discuss some things in more detail..

1. I don't really think the executor should know anything about signing. Executor should be dumb and only handle OS-level stuff and not be cognizant of anything else. It takes care of setting up the working directory and cleans up afterwards, sets the process resource limits and executes the process (OS-level `exec()` type stuff). I don't think the concept of signing fits well here and I think it's mixing up concerns. I think this would be more suited in the `node` package and the `node` signs the execution result the executor returns. Basically, I would just move this code to a different place.

2. I'm not sure the aggregation part is working correctly. Commented in more detail on the relevant part of the code.

3. If the workers can choose their own signing scheme, we need to pass along the information on what scheme was used, no? It cannot be unlabeled else we don't know how to verify the signature. Also ties into discussion point 4.

4. Does it make sense for each worker to have the freedom to choose their signing schemes? IMO, they can choose which ones they support, but perhaps it's the client that can request a specific one in the execution request. If a client didn't set one, a head node can request a default scheme we choose, or not use any by default. The workers can then self-select - "if I don't support this signing scheme I won't reply to a roll call". This is super close to what we have with b7s attributes too. Though, at the moment, the attributes are only a strict match, and we don't support a syntax like `B7S_SignatureAlgorithms=A,B,C,D` to match "C". This is relevant if the node supports multiple signing schemes.

If we do move the signing code to the `node` package, we need to handle three main paths
- simple execution (no consensus cluster) - https://github.com/blocklessnetwork/b7s/blob/main/node/worker_execute.go#L86
- raft cluster - https://github.com/blocklessnetwork/b7s/blob/main/node/consensus.go#L36 . Perhaps we modify the callback signature so it can modify the original request so it can add more data to it
- pbft cluster - https://github.com/blocklessnetwork/b7s/blob/main/consensus/pbft/execute.go#L73 (Note that PBFT mandates signatures - so workers cannot opt out of signing these)

I may be wrong on any one of these points or I might have misunderstood something, so feel free to correct me!

2024-06-24 14:25 UTC, Maelkum commented on consensus/pbft/execute.go
> +		Signature: hex.EncodeToString(res.Signature),
PBFT already has and mandates signatures - note the `msg.Sign()` invocation below that will overwrite this value.

2024-06-28 08:32 UTC, zees-dev commented
Closing this PR in favour of https://github.com/blocklessnetwork/b7s/pull/156

2024-06-28 08:32 UTC, closed without merging